version: "3.8"
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      -  POSTGRES_USER=expenses
      -  POSTGRES_DATABASE=expenses
      -  POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: {}
